# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/object_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/object_server.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1aprotos/object_server.proto\"1\n\rObjectRequest\x12\n\n\x02ws\x18\x01 \x01(\t\x12\x14\n\x05\x61reas\x18\x02 \x03(\x0b\x32\x05.Area\"\x1d\n\x0eObjectResponse\x12\x0b\n\x03\x66ps\x18\x01 \x01(\t\"5\n\x04\x41rea\x12\x0f\n\x07\x61rea_id\x18\x01 \x01(\t\x12\x1c\n\x0e\x64\x65tection_area\x18\x02 \x01(\x0b\x32\x04.Box\"X\n\x13\x43ountObjectResponse\x12.\n\x0f\x63ounted_Objects\x18\x01 \x03(\x0b\x32\x15.CountedObjectsByArea\x12\x11\n\ttimestamp\x18\x02 \x01(\x02\"^\n\x14\x43ountedObjectsByArea\x12\x0f\n\x07\x61rea_id\x18\x01 \x01(\t\x12\x14\n\x0ctotal_Object\x18\x02 \x01(\x05\x12\x1f\n\x06\x64\x65tail\x18\x03 \x03(\x0b\x32\x0f.CountedObjects\"Z\n\x0e\x43ountedObjects\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12\x13\n\x0bObject_type\x18\x02 \x01(\t\x12$\n\x16\x63urrent_bounding_boxes\x18\x03 \x03(\x0b\x32\x04.Box\":\n\x03\x42ox\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\x32\xcf\x01\n\rObjectService\x12?\n\x13ViolateObjectDetect\x12\x0e.ObjectRequest\x1a\x14.CountObjectResponse\"\x00\x30\x01\x12=\n\x11LeaveObjectDetect\x12\x0e.ObjectRequest\x1a\x14.CountObjectResponse\"\x00\x30\x01\x12>\n\x12\x46orgotObjectDetect\x12\x0e.ObjectRequest\x1a\x14.CountObjectResponse\"\x00\x30\x01\x62\x06proto3'
)




_OBJECTREQUEST = _descriptor.Descriptor(
  name='ObjectRequest',
  full_name='ObjectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ws', full_name='ObjectRequest.ws', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='areas', full_name='ObjectRequest.areas', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=79,
)


_OBJECTRESPONSE = _descriptor.Descriptor(
  name='ObjectResponse',
  full_name='ObjectResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fps', full_name='ObjectResponse.fps', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=110,
)


_AREA = _descriptor.Descriptor(
  name='Area',
  full_name='Area',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='area_id', full_name='Area.area_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='detection_area', full_name='Area.detection_area', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=165,
)


_COUNTOBJECTRESPONSE = _descriptor.Descriptor(
  name='CountObjectResponse',
  full_name='CountObjectResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='counted_Objects', full_name='CountObjectResponse.counted_Objects', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='CountObjectResponse.timestamp', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=255,
)


_COUNTEDOBJECTSBYAREA = _descriptor.Descriptor(
  name='CountedObjectsByArea',
  full_name='CountedObjectsByArea',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='area_id', full_name='CountedObjectsByArea.area_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_Object', full_name='CountedObjectsByArea.total_Object', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='detail', full_name='CountedObjectsByArea.detail', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=351,
)


_COUNTEDOBJECTS = _descriptor.Descriptor(
  name='CountedObjects',
  full_name='CountedObjects',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='CountedObjects.count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Object_type', full_name='CountedObjects.Object_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current_bounding_boxes', full_name='CountedObjects.current_bounding_boxes', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=353,
  serialized_end=443,
)


_BOX = _descriptor.Descriptor(
  name='Box',
  full_name='Box',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Box.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='Box.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='width', full_name='Box.width', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='Box.height', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=445,
  serialized_end=503,
)

_OBJECTREQUEST.fields_by_name['areas'].message_type = _AREA
_AREA.fields_by_name['detection_area'].message_type = _BOX
_COUNTOBJECTRESPONSE.fields_by_name['counted_Objects'].message_type = _COUNTEDOBJECTSBYAREA
_COUNTEDOBJECTSBYAREA.fields_by_name['detail'].message_type = _COUNTEDOBJECTS
_COUNTEDOBJECTS.fields_by_name['current_bounding_boxes'].message_type = _BOX
DESCRIPTOR.message_types_by_name['ObjectRequest'] = _OBJECTREQUEST
DESCRIPTOR.message_types_by_name['ObjectResponse'] = _OBJECTRESPONSE
DESCRIPTOR.message_types_by_name['Area'] = _AREA
DESCRIPTOR.message_types_by_name['CountObjectResponse'] = _COUNTOBJECTRESPONSE
DESCRIPTOR.message_types_by_name['CountedObjectsByArea'] = _COUNTEDOBJECTSBYAREA
DESCRIPTOR.message_types_by_name['CountedObjects'] = _COUNTEDOBJECTS
DESCRIPTOR.message_types_by_name['Box'] = _BOX
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ObjectRequest = _reflection.GeneratedProtocolMessageType('ObjectRequest', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTREQUEST,
  '__module__' : 'protos.object_server_pb2'
  # @@protoc_insertion_point(class_scope:ObjectRequest)
  })
_sym_db.RegisterMessage(ObjectRequest)

ObjectResponse = _reflection.GeneratedProtocolMessageType('ObjectResponse', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTRESPONSE,
  '__module__' : 'protos.object_server_pb2'
  # @@protoc_insertion_point(class_scope:ObjectResponse)
  })
_sym_db.RegisterMessage(ObjectResponse)

Area = _reflection.GeneratedProtocolMessageType('Area', (_message.Message,), {
  'DESCRIPTOR' : _AREA,
  '__module__' : 'protos.object_server_pb2'
  # @@protoc_insertion_point(class_scope:Area)
  })
_sym_db.RegisterMessage(Area)

CountObjectResponse = _reflection.GeneratedProtocolMessageType('CountObjectResponse', (_message.Message,), {
  'DESCRIPTOR' : _COUNTOBJECTRESPONSE,
  '__module__' : 'protos.object_server_pb2'
  # @@protoc_insertion_point(class_scope:CountObjectResponse)
  })
_sym_db.RegisterMessage(CountObjectResponse)

CountedObjectsByArea = _reflection.GeneratedProtocolMessageType('CountedObjectsByArea', (_message.Message,), {
  'DESCRIPTOR' : _COUNTEDOBJECTSBYAREA,
  '__module__' : 'protos.object_server_pb2'
  # @@protoc_insertion_point(class_scope:CountedObjectsByArea)
  })
_sym_db.RegisterMessage(CountedObjectsByArea)

CountedObjects = _reflection.GeneratedProtocolMessageType('CountedObjects', (_message.Message,), {
  'DESCRIPTOR' : _COUNTEDOBJECTS,
  '__module__' : 'protos.object_server_pb2'
  # @@protoc_insertion_point(class_scope:CountedObjects)
  })
_sym_db.RegisterMessage(CountedObjects)

Box = _reflection.GeneratedProtocolMessageType('Box', (_message.Message,), {
  'DESCRIPTOR' : _BOX,
  '__module__' : 'protos.object_server_pb2'
  # @@protoc_insertion_point(class_scope:Box)
  })
_sym_db.RegisterMessage(Box)



_OBJECTSERVICE = _descriptor.ServiceDescriptor(
  name='ObjectService',
  full_name='ObjectService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=506,
  serialized_end=713,
  methods=[
  _descriptor.MethodDescriptor(
    name='ViolateObjectDetect',
    full_name='ObjectService.ViolateObjectDetect',
    index=0,
    containing_service=None,
    input_type=_OBJECTREQUEST,
    output_type=_COUNTOBJECTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='LeaveObjectDetect',
    full_name='ObjectService.LeaveObjectDetect',
    index=1,
    containing_service=None,
    input_type=_OBJECTREQUEST,
    output_type=_COUNTOBJECTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ForgotObjectDetect',
    full_name='ObjectService.ForgotObjectDetect',
    index=2,
    containing_service=None,
    input_type=_OBJECTREQUEST,
    output_type=_COUNTOBJECTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_OBJECTSERVICE)

DESCRIPTOR.services_by_name['ObjectService'] = _OBJECTSERVICE

# @@protoc_insertion_point(module_scope)
